language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - pip install numpy==1.8.0 quantities==0.10.1 --use-mirrors
# command to run tests
script:
  - python setup.py test
